version: '3.1'

services:
  postgresql:
    image: postgres:12
    container_name: new-pg
    ports:
      - '6432:5432'
    volumes:
      - '/opt/volume/pgbackup:/opt/pgbackup'
      - '/opt/volume/files:/opt/files'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'POSTGRES_PASSWORD=1234'
    restart: always

volumes:
  postgresql_data:
    driver: local